# Site settings
title: Share is better
email: huiyiqun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog. I'm glad to share my memory here. Hope that I could
  help you.
  This is about network, life of nerd or anything else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huiyiqun.github.io" # the base hostname & protocol for your site
#twitter_username:
github_username:  huiyiqun

# Build settings
markdown: kramdown
